/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "E:\\study\\博客\\reco博客\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-b5739e4c",
    path: "/docs/One Piece/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b5739e4c").then(next)
    },
  },
  {
    path: "/docs/One Piece/index.html",
    redirect: "/docs/One Piece/"
  },
  {
    path: "/One Piece/",
    redirect: "/docs/One Piece/"
  },
  {
    name: "v-8b5f3892",
    path: "/docs/JavaScript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8b5f3892").then(next)
    },
  },
  {
    path: "/docs/JavaScript/index.html",
    redirect: "/docs/JavaScript/"
  },
  {
    path: "/JavaScript/",
    redirect: "/docs/JavaScript/"
  },
  {
    name: "v-554ff474",
    path: "/docs/JavaScript/js数据类型判断/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-554ff474").then(next)
    },
  },
  {
    path: "/docs/JavaScript/js数据类型判断/index.html",
    redirect: "/docs/JavaScript/js数据类型判断/"
  },
  {
    path: "/JavaScript/js数据类型判断.html",
    redirect: "/docs/JavaScript/js数据类型判断/"
  },
  {
    name: "v-56be3ca8",
    path: "/docs/JavaScript/去重/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-56be3ca8").then(next)
    },
  },
  {
    path: "/docs/JavaScript/去重/index.html",
    redirect: "/docs/JavaScript/去重/"
  },
  {
    path: "/JavaScript/去重.html",
    redirect: "/docs/JavaScript/去重/"
  },
  {
    name: "v-13d57ec9",
    path: "/docs/One Piece/composition组合式API/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-13d57ec9").then(next)
    },
  },
  {
    path: "/docs/One Piece/composition组合式API/index.html",
    redirect: "/docs/One Piece/composition组合式API/"
  },
  {
    path: "/One Piece/composition组合式API.html",
    redirect: "/docs/One Piece/composition组合式API/"
  },
  {
    name: "v-35e1deb6",
    path: "/docs/TypeScript/接口/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-35e1deb6").then(next)
    },
  },
  {
    path: "/docs/TypeScript/接口/index.html",
    redirect: "/docs/TypeScript/接口/"
  },
  {
    path: "/TypeScript/接口.html",
    redirect: "/docs/TypeScript/接口/"
  },
  {
    name: "v-7f41aa77",
    path: "/docs/TypeScript/函数/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7f41aa77").then(next)
    },
  },
  {
    path: "/docs/TypeScript/函数/index.html",
    redirect: "/docs/TypeScript/函数/"
  },
  {
    path: "/TypeScript/函数.html",
    redirect: "/docs/TypeScript/函数/"
  },
  {
    name: "v-0ccd49f1",
    path: "/docs/TypeScript/数据类型/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0ccd49f1").then(next)
    },
  },
  {
    path: "/docs/TypeScript/数据类型/index.html",
    redirect: "/docs/TypeScript/数据类型/"
  },
  {
    path: "/TypeScript/数据类型.html",
    redirect: "/docs/TypeScript/数据类型/"
  },
  {
    name: "v-3697d243",
    path: "/docs/One Piece/新组件/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3697d243").then(next)
    },
  },
  {
    path: "/docs/One Piece/新组件/index.html",
    redirect: "/docs/One Piece/新组件/"
  },
  {
    path: "/One Piece/新组件.html",
    redirect: "/docs/One Piece/新组件/"
  },
  {
    name: "v-fe163692",
    path: "/docs/TypeScript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fe163692").then(next)
    },
  },
  {
    path: "/docs/TypeScript/index.html",
    redirect: "/docs/TypeScript/"
  },
  {
    path: "/TypeScript/",
    redirect: "/docs/TypeScript/"
  },
  {
    name: "v-3298eb82",
    path: "/docs/TypeScript/泛型/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3298eb82").then(next)
    },
  },
  {
    path: "/docs/TypeScript/泛型/index.html",
    redirect: "/docs/TypeScript/泛型/"
  },
  {
    path: "/TypeScript/泛型.html",
    redirect: "/docs/TypeScript/泛型/"
  },
  {
    name: "v-6268951e",
    path: "/docs/TypeScript/类/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6268951e").then(next)
    },
  },
  {
    path: "/docs/TypeScript/类/index.html",
    redirect: "/docs/TypeScript/类/"
  },
  {
    path: "/TypeScript/类.html",
    redirect: "/docs/TypeScript/类/"
  },
  {
    name: "v-7b9b609a",
    path: "/docs/VUE/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7b9b609a").then(next)
    },
  },
  {
    path: "/docs/VUE/index.html",
    redirect: "/docs/VUE/"
  },
  {
    path: "/VUE/",
    redirect: "/docs/VUE/"
  },
  {
    name: "v-26da29a4",
    path: "/docs/VUE/vue开发技巧/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-26da29a4").then(next)
    },
  },
  {
    path: "/docs/VUE/vue开发技巧/index.html",
    redirect: "/docs/VUE/vue开发技巧/"
  },
  {
    path: "/VUE/vue开发技巧.html",
    redirect: "/docs/VUE/vue开发技巧/"
  },
  {
    name: "v-50fed877",
    path: "/docs/VUE/VUE的指令/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-50fed877").then(next)
    },
  },
  {
    path: "/docs/VUE/VUE的指令/index.html",
    redirect: "/docs/VUE/VUE的指令/"
  },
  {
    path: "/VUE/VUE的指令.html",
    redirect: "/docs/VUE/VUE的指令/"
  },
  {
    name: "v-317f572f",
    path: "/docs/VUE/computed和watch/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-317f572f").then(next)
    },
  },
  {
    path: "/docs/VUE/computed和watch/index.html",
    redirect: "/docs/VUE/computed和watch/"
  },
  {
    path: "/VUE/computed和watch.html",
    redirect: "/docs/VUE/computed和watch/"
  },
  {
    name: "v-7368a04b",
    path: "/docs/VUE/传参方式/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7368a04b").then(next)
    },
  },
  {
    path: "/docs/VUE/传参方式/index.html",
    redirect: "/docs/VUE/传参方式/"
  },
  {
    path: "/VUE/传参方式.html",
    redirect: "/docs/VUE/传参方式/"
  },
  {
    name: "v-d6c13f38",
    path: "/docs/VUE/列表滚动/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d6c13f38").then(next)
    },
  },
  {
    path: "/docs/VUE/列表滚动/index.html",
    redirect: "/docs/VUE/列表滚动/"
  },
  {
    path: "/VUE/列表滚动.html",
    redirect: "/docs/VUE/列表滚动/"
  },
  {
    name: "v-4dce1a64",
    path: "/docs/VUE/生命周期/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4dce1a64").then(next)
    },
  },
  {
    path: "/docs/VUE/生命周期/index.html",
    redirect: "/docs/VUE/生命周期/"
  },
  {
    path: "/VUE/生命周期.html",
    redirect: "/docs/VUE/生命周期/"
  },
  {
    name: "v-a9ea0072",
    path: "/docs/VUE/组件缓存/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a9ea0072").then(next)
    },
  },
  {
    path: "/docs/VUE/组件缓存/index.html",
    redirect: "/docs/VUE/组件缓存/"
  },
  {
    path: "/VUE/组件缓存.html",
    redirect: "/docs/VUE/组件缓存/"
  },
  {
    name: "v-d3a634e2",
    path: "/docs/VUE/路由/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d3a634e2").then(next)
    },
  },
  {
    path: "/docs/VUE/路由/index.html",
    redirect: "/docs/VUE/路由/"
  },
  {
    path: "/VUE/路由.html",
    redirect: "/docs/VUE/路由/"
  },
  {
    name: "v-ee7ffc08",
    path: "/docs/cesium三维地图/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ee7ffc08").then(next)
    },
  },
  {
    path: "/docs/cesium三维地图/index.html",
    redirect: "/docs/cesium三维地图/"
  },
  {
    path: "/cesium三维地图/点位聚合.html",
    redirect: "/docs/cesium三维地图/"
  },
  {
    name: "v-187027f6",
    path: "/docs/cesium三维地图/地图坐标以及点击弹框/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-187027f6").then(next)
    },
  },
  {
    path: "/docs/cesium三维地图/地图坐标以及点击弹框/index.html",
    redirect: "/docs/cesium三维地图/地图坐标以及点击弹框/"
  },
  {
    path: "/cesium三维地图/地图坐标以及点击弹框.html",
    redirect: "/docs/cesium三维地图/地图坐标以及点击弹框/"
  },
  {
    name: "v-2265c176",
    path: "/docs/cesium三维地图/坐标地面闪烁/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2265c176").then(next)
    },
  },
  {
    path: "/docs/cesium三维地图/坐标地面闪烁/index.html",
    redirect: "/docs/cesium三维地图/坐标地面闪烁/"
  },
  {
    path: "/cesium三维地图/坐标地面闪烁.html",
    redirect: "/docs/cesium三维地图/坐标地面闪烁/"
  },
  {
    name: "v-de48b46a",
    path: "/docs/cesium三维地图/cesium配置/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-de48b46a").then(next)
    },
  },
  {
    path: "/docs/cesium三维地图/cesium配置/index.html",
    redirect: "/docs/cesium三维地图/cesium配置/"
  },
  {
    path: "/cesium三维地图/cesium配置.html",
    redirect: "/docs/cesium三维地图/cesium配置/"
  },
  {
    name: "v-0ddcc835",
    path: "/docs/cesium三维地图/添加一个立方体/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0ddcc835").then(next)
    },
  },
  {
    path: "/docs/cesium三维地图/添加一个立方体/index.html",
    redirect: "/docs/cesium三维地图/添加一个立方体/"
  },
  {
    path: "/cesium三维地图/添加一个立方体.html",
    redirect: "/docs/cesium三维地图/添加一个立方体/"
  },
  {
    name: "v-88d19402",
    path: "/docs/cesium三维地图/点位起飞并有落地线/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-88d19402").then(next)
    },
  },
  {
    path: "/docs/cesium三维地图/点位起飞并有落地线/index.html",
    redirect: "/docs/cesium三维地图/点位起飞并有落地线/"
  },
  {
    path: "/cesium三维地图/点位起飞并有落地线.html",
    redirect: "/docs/cesium三维地图/点位起飞并有落地线/"
  },
  {
    name: "v-db3d082a",
    path: "/docs/cesium三维地图/离线地图瓦片引用/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-db3d082a").then(next)
    },
  },
  {
    path: "/docs/cesium三维地图/离线地图瓦片引用/index.html",
    redirect: "/docs/cesium三维地图/离线地图瓦片引用/"
  },
  {
    path: "/cesium三维地图/离线地图瓦片引用.html",
    redirect: "/docs/cesium三维地图/离线地图瓦片引用/"
  },
  {
    name: "v-ab19c3ae",
    path: "/docs/博客/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ab19c3ae").then(next)
    },
  },
  {
    path: "/docs/博客/index.html",
    redirect: "/docs/博客/"
  },
  {
    path: "/博客搭建/",
    redirect: "/docs/博客/"
  },
  {
    name: "v-21a94ace",
    path: "/docs/博客/侧边栏/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-21a94ace").then(next)
    },
  },
  {
    path: "/docs/博客/侧边栏/index.html",
    redirect: "/docs/博客/侧边栏/"
  },
  {
    path: "/博客搭建/侧边栏.html",
    redirect: "/docs/博客/侧边栏/"
  },
  {
    name: "v-5ef0e5ee",
    path: "/docs/博客/插件大全/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5ef0e5ee").then(next)
    },
  },
  {
    path: "/docs/博客/插件大全/index.html",
    redirect: "/docs/博客/插件大全/"
  },
  {
    path: "/博客搭建/插件大全.html",
    redirect: "/docs/博客/插件大全/"
  },
  {
    name: "v-f4f8dc48",
    path: "/docs/博客/插件的使用/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f4f8dc48").then(next)
    },
  },
  {
    path: "/docs/博客/插件的使用/index.html",
    redirect: "/docs/博客/插件的使用/"
  },
  {
    path: "/博客搭建/插件的使用.html",
    redirect: "/docs/博客/插件的使用/"
  },
  {
    name: "v-80e439d2",
    path: "/docs/博客/部署github和gitee/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-80e439d2").then(next)
    },
  },
  {
    path: "/docs/博客/部署github和gitee/index.html",
    redirect: "/docs/博客/部署github和gitee/"
  },
  {
    path: "/博客搭建/部署github和gitee.html",
    redirect: "/docs/博客/部署github和gitee/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]