/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "One Piece",
      "frontmatter": {
        "title": "One Piece",
        "date": "2022-9-27",
        "permalink": "/docs/One Piece/",
        "autoSort": 20,
        "tags": [
          "One Piece"
        ],
        "categories": [
          "One Piece"
        ]
      },
      "regularPath": "/One%20Piece/",
      "relativePath": "One Piece/README.md",
      "key": "v-b5739e4c",
      "path": "/docs/One Piece/",
      "headers": [
        {
          "level": 2,
          "title": "那些改变",
          "slug": "那些改变"
        },
        {
          "level": 2,
          "title": "新增",
          "slug": "新增"
        },
        {
          "level": 2,
          "title": "创建VUE3项目",
          "slug": "创建vue3项目"
        },
        {
          "level": 3,
          "title": "使用vue/cli 安装",
          "slug": "使用vue-cli-安装"
        },
        {
          "level": 3,
          "title": "使用vite安装",
          "slug": "使用vite安装"
        }
      ],
      "excerpt": "<p><img src=\"https://s1.ax1x.com/2022/09/30/xuJ228.png\" alt=\"11\"></p>\n"
    },
    {
      "title": "JavaScript",
      "frontmatter": {
        "title": "JavaScript",
        "date": "2022-5-30",
        "permalink": "/docs/JavaScript/",
        "autoSort": 20,
        "tags": [
          "JavaScript"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/JavaScript/",
      "relativePath": "JavaScript/README.md",
      "key": "v-8b5f3892",
      "path": "/docs/JavaScript/"
    },
    {
      "title": "js数据类型判断",
      "frontmatter": {
        "title": "js数据类型判断",
        "date": "2022-8-8",
        "permalink": "/docs/JavaScript/js数据类型判断",
        "autoSort": 20,
        "tags": [
          "JavaScript"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/JavaScript/js%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B%E5%88%A4%E6%96%AD.html",
      "relativePath": "JavaScript/js数据类型判断.md",
      "key": "v-554ff474",
      "path": "/docs/JavaScript/js数据类型判断/",
      "headers": [
        {
          "level": 2,
          "title": "JS的数据类型",
          "slug": "js的数据类型"
        },
        {
          "level": 3,
          "title": "JS的数据类型分为以下两类",
          "slug": "js的数据类型分为以下两类"
        },
        {
          "level": 3,
          "title": "基本类型和引用类型的区别",
          "slug": "基本类型和引用类型的区别"
        },
        {
          "level": 3,
          "title": "为什么字符串有length属性 ？",
          "slug": "为什么字符串有length属性"
        },
        {
          "level": 2,
          "title": "JS的类型判断方式",
          "slug": "js的类型判断方式"
        },
        {
          "level": 3,
          "title": "Object.prototype.toString.call()",
          "slug": "object-prototype-tostring-call"
        },
        {
          "level": 3,
          "title": "typeof()",
          "slug": "typeof"
        },
        {
          "level": 3,
          "title": "instanceof()",
          "slug": "instanceof"
        },
        {
          "level": 3,
          "title": "特定的判断方法",
          "slug": "特定的判断方法"
        },
        {
          "level": 2,
          "title": "JS的类型转换",
          "slug": "js的类型转换"
        },
        {
          "level": 3,
          "title": "显示类型转换，人为操作",
          "slug": "显示类型转换-人为操作"
        }
      ]
    },
    {
      "title": "去重",
      "frontmatter": {
        "title": "去重",
        "date": "2022-10-11T00:00:00.000Z",
        "permalink": "/docs/JavaScript/去重",
        "autoSort": 19,
        "tags": [
          "JavaScript"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/JavaScript/%E5%8E%BB%E9%87%8D.html",
      "relativePath": "JavaScript/去重.md",
      "key": "v-56be3ca8",
      "path": "/docs/JavaScript/去重/",
      "headers": [
        {
          "level": 2,
          "title": "reduce去重",
          "slug": "reduce去重"
        }
      ]
    },
    {
      "title": "composition组合式API",
      "frontmatter": {
        "title": "composition组合式API",
        "date": "2022-9-27",
        "permalink": "/docs/One Piece/composition组合式API",
        "autoSort": 20,
        "tags": [
          "One Piece"
        ],
        "categories": [
          "One Piece"
        ]
      },
      "regularPath": "/One%20Piece/composition%E7%BB%84%E5%90%88%E5%BC%8FAPI.html",
      "relativePath": "One Piece/composition组合式API.md",
      "key": "v-13d57ec9",
      "path": "/docs/One Piece/composition组合式API/",
      "headers": [
        {
          "level": 2,
          "title": "setup",
          "slug": "setup"
        },
        {
          "level": 3,
          "title": "简单用法",
          "slug": "简单用法"
        },
        {
          "level": 3,
          "title": "setup细节问题",
          "slug": "setup细节问题"
        },
        {
          "level": 2,
          "title": "ref与reactive",
          "slug": "ref与reactive"
        },
        {
          "level": 3,
          "title": "ref",
          "slug": "ref"
        },
        {
          "level": 3,
          "title": "reactive",
          "slug": "reactive"
        },
        {
          "level": 3,
          "title": "vue2和vue3响应式原理不同",
          "slug": "vue2和vue3响应式原理不同"
        },
        {
          "level": 2,
          "title": "computed 和 watch （计算属性和监听属性）",
          "slug": "computed-和-watch-计算属性和监听属性"
        },
        {
          "level": 3,
          "title": "computed",
          "slug": "computed"
        },
        {
          "level": 3,
          "title": "watch",
          "slug": "watch"
        },
        {
          "level": 3,
          "title": "watchEffect",
          "slug": "watcheffect"
        },
        {
          "level": 2,
          "title": "生命周期",
          "slug": "生命周期"
        },
        {
          "level": 2,
          "title": "自定义hook",
          "slug": "自定义hook"
        },
        {
          "level": 2,
          "title": "shallowReactive和shallowRef",
          "slug": "shallowreactive和shallowref"
        },
        {
          "level": 2,
          "title": "readonly和shallowReadonly",
          "slug": "readonly和shallowreadonly"
        },
        {
          "level": 2,
          "title": "toRaw 与 markRaw",
          "slug": "toraw-与-markraw"
        },
        {
          "level": 2,
          "title": "toRef",
          "slug": "toref"
        },
        {
          "level": 2,
          "title": "customRef",
          "slug": "customref"
        },
        {
          "level": 2,
          "title": "provide 与 inject",
          "slug": "provide-与-inject"
        }
      ]
    },
    {
      "title": "接口",
      "frontmatter": {
        "title": "接口",
        "date": "2022-9-8",
        "permalink": "/docs/TypeScript/接口",
        "autoSort": 10,
        "tags": [
          "TypeScript"
        ],
        "categories": [
          "TypeScript"
        ]
      },
      "regularPath": "/TypeScript/%E6%8E%A5%E5%8F%A3.html",
      "relativePath": "TypeScript/接口.md",
      "key": "v-35e1deb6",
      "path": "/docs/TypeScript/接口/",
      "headers": [
        {
          "level": 2,
          "title": "初步演示",
          "slug": "初步演示"
        }
      ]
    },
    {
      "title": "函数",
      "frontmatter": {
        "title": "函数",
        "date": "2022-9-26",
        "permalink": "/docs/TypeScript/函数",
        "autoSort": 9,
        "tags": [
          "TypeScript"
        ],
        "categories": [
          "TypeScript"
        ]
      },
      "regularPath": "/TypeScript/%E5%87%BD%E6%95%B0.html",
      "relativePath": "TypeScript/函数.md",
      "key": "v-7f41aa77",
      "path": "/docs/TypeScript/函数/",
      "headers": [
        {
          "level": 2,
          "title": "写法",
          "slug": "写法"
        },
        {
          "level": 3,
          "title": "命名函数",
          "slug": "命名函数"
        },
        {
          "level": 3,
          "title": "匿名函数",
          "slug": "匿名函数"
        },
        {
          "level": 3,
          "title": "完整写法",
          "slug": "完整写法"
        },
        {
          "level": 2,
          "title": "可选参数和默认参数",
          "slug": "可选参数和默认参数"
        },
        {
          "level": 2,
          "title": "剩余参数",
          "slug": "剩余参数"
        },
        {
          "level": 2,
          "title": "函数重载",
          "slug": "函数重载"
        }
      ]
    },
    {
      "title": "数据类型",
      "frontmatter": {
        "title": "数据类型",
        "date": "2022-9-8",
        "permalink": "/docs/TypeScript/数据类型",
        "autoSort": 19,
        "tags": [
          "TypeScript"
        ],
        "categories": [
          "TypeScript"
        ]
      },
      "regularPath": "/TypeScript/%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B.html",
      "relativePath": "TypeScript/数据类型.md",
      "key": "v-0ccd49f1",
      "path": "/docs/TypeScript/数据类型/",
      "headers": [
        {
          "level": 2,
          "title": "基础数据类型",
          "slug": "基础数据类型"
        },
        {
          "level": 3,
          "title": "布尔值",
          "slug": "布尔值"
        },
        {
          "level": 3,
          "title": "数值",
          "slug": "数值"
        },
        {
          "level": 3,
          "title": "字符串",
          "slug": "字符串"
        },
        {
          "level": 3,
          "title": "void",
          "slug": "void"
        },
        {
          "level": 3,
          "title": "Null 和 Undefined",
          "slug": "null-和-undefined"
        },
        {
          "level": 3,
          "title": "数组",
          "slug": "数组"
        },
        {
          "level": 3,
          "title": "枚举",
          "slug": "枚举"
        },
        {
          "level": 3,
          "title": "any",
          "slug": "any"
        },
        {
          "level": 3,
          "title": "object",
          "slug": "object"
        },
        {
          "level": 3,
          "title": "联合类型",
          "slug": "联合类型"
        },
        {
          "level": 3,
          "title": "类型断言",
          "slug": "类型断言"
        }
      ]
    },
    {
      "title": "新组件",
      "frontmatter": {
        "title": "新组件",
        "date": "2022-10-10T00:00:00.000Z",
        "permalink": "/docs/One Piece/新组件",
        "autoSort": 21,
        "tags": [
          "One Piece"
        ],
        "categories": [
          "One Piece"
        ]
      },
      "regularPath": "/One%20Piece/%E6%96%B0%E7%BB%84%E4%BB%B6.html",
      "relativePath": "One Piece/新组件.md",
      "key": "v-3697d243",
      "path": "/docs/One Piece/新组件/",
      "headers": [
        {
          "level": 2,
          "title": "Fragment(片段)",
          "slug": "fragment-片段"
        },
        {
          "level": 2,
          "title": "Teleport(瞬移)",
          "slug": "teleport-瞬移"
        },
        {
          "level": 2,
          "title": "Suspense(不确定)",
          "slug": "suspense-不确定"
        }
      ]
    },
    {
      "title": "TypeScript",
      "frontmatter": {
        "title": "TypeScript",
        "date": "2022-9-8",
        "permalink": "/docs/TypeScript/",
        "autoSort": 20,
        "tags": [
          "TypeScript"
        ],
        "categories": [
          "TypeScript"
        ]
      },
      "regularPath": "/TypeScript/",
      "relativePath": "TypeScript/README.md",
      "key": "v-fe163692",
      "path": "/docs/TypeScript/",
      "headers": [
        {
          "level": 2,
          "title": "什么是 TypeScript",
          "slug": "什么是-typescript"
        },
        {
          "level": 2,
          "title": "安装 TypeScript",
          "slug": "安装-typescript"
        },
        {
          "level": 2,
          "title": "自动编译js文件",
          "slug": "自动编译js文件"
        }
      ]
    },
    {
      "title": "泛型",
      "frontmatter": {
        "title": "泛型",
        "date": "2022-9-26",
        "permalink": "/docs/TypeScript/泛型",
        "autoSort": 8,
        "tags": [
          "TypeScript"
        ],
        "categories": [
          "TypeScript"
        ]
      },
      "regularPath": "/TypeScript/%E6%B3%9B%E5%9E%8B.html",
      "relativePath": "TypeScript/泛型.md",
      "key": "v-3298eb82",
      "path": "/docs/TypeScript/泛型/",
      "headers": [
        {
          "level": 2,
          "title": "用法",
          "slug": "用法"
        },
        {
          "level": 2,
          "title": "多个泛型参数",
          "slug": "多个泛型参数"
        },
        {
          "level": 2,
          "title": "泛型接口",
          "slug": "泛型接口"
        },
        {
          "level": 2,
          "title": "泛型类",
          "slug": "泛型类"
        },
        {
          "level": 2,
          "title": "泛型约束",
          "slug": "泛型约束"
        }
      ]
    },
    {
      "title": "类",
      "frontmatter": {
        "title": "类",
        "date": "2022-9-8",
        "permalink": "/docs/TypeScript/类",
        "autoSort": 9,
        "tags": [
          "TypeScript"
        ],
        "categories": [
          "TypeScript"
        ]
      },
      "regularPath": "/TypeScript/%E7%B1%BB.html",
      "relativePath": "TypeScript/类.md",
      "key": "v-6268951e",
      "path": "/docs/TypeScript/类/",
      "headers": [
        {
          "level": 2,
          "title": "初步认识",
          "slug": "初步认识"
        },
        {
          "level": 2,
          "title": "继承",
          "slug": "继承"
        },
        {
          "level": 2,
          "title": "公共、私有、受保护修饰符",
          "slug": "公共、私有、受保护修饰符"
        },
        {
          "level": 2,
          "title": "readonly只读修饰符",
          "slug": "readonly只读修饰符"
        },
        {
          "level": 2,
          "title": "存取器",
          "slug": "存取器"
        },
        {
          "level": 2,
          "title": "静态成员",
          "slug": "静态成员"
        }
      ]
    },
    {
      "title": "VUE的搭建",
      "frontmatter": {
        "title": "VUE的搭建",
        "date": "2022-5-30",
        "permalink": "/docs/VUE/",
        "autoSort": 20,
        "tags": [
          "VUE"
        ],
        "categories": [
          "VUE"
        ]
      },
      "regularPath": "/VUE/",
      "relativePath": "VUE/README.md",
      "key": "v-7b9b609a",
      "path": "/docs/VUE/",
      "headers": [
        {
          "level": 2,
          "title": "使用脚手架搭建",
          "slug": "使用脚手架搭建"
        },
        {
          "level": 3,
          "title": "安装命令",
          "slug": "安装命令"
        },
        {
          "level": 3,
          "title": "配置淘宝镜像",
          "slug": "配置淘宝镜像"
        },
        {
          "level": 3,
          "title": "vue不是内部命令问题",
          "slug": "vue不是内部命令问题"
        },
        {
          "level": 3,
          "title": "创建一个项目",
          "slug": "创建一个项目"
        }
      ]
    },
    {
      "title": "vue开发技巧",
      "frontmatter": {
        "title": "vue开发技巧",
        "date": "2022-7-11",
        "permalink": "/docs/VUE/vue开发技巧",
        "autoSort": 0,
        "tags": [
          "VUE"
        ],
        "categories": [
          "VUE"
        ]
      },
      "regularPath": "/VUE/vue%E5%BC%80%E5%8F%91%E6%8A%80%E5%B7%A7.html",
      "relativePath": "VUE/vue开发技巧.md",
      "key": "v-26da29a4",
      "path": "/docs/VUE/vue开发技巧/",
      "headers": [
        {
          "level": 2,
          "title": "require.context()",
          "slug": "require-context"
        },
        {
          "level": 2,
          "title": "组件通信",
          "slug": "组件通信"
        },
        {
          "level": 3,
          "title": "props写法",
          "slug": "props写法"
        },
        {
          "level": 3,
          "title": "$emit",
          "slug": "emit"
        },
        {
          "level": 3,
          "title": "attrs和listeners",
          "slug": "attrs和listeners"
        },
        {
          "level": 2,
          "title": "render 函数",
          "slug": "render-函数"
        }
      ]
    },
    {
      "title": "VUE的指令",
      "frontmatter": {
        "title": "VUE的指令",
        "date": "2022-7-19",
        "permalink": "/docs/VUE/VUE的指令",
        "autoSort": 19,
        "tags": [
          "VUE"
        ],
        "categories": [
          "VUE"
        ]
      },
      "regularPath": "/VUE/VUE%E7%9A%84%E6%8C%87%E4%BB%A4.html",
      "relativePath": "VUE/VUE的指令.md",
      "key": "v-50fed877",
      "path": "/docs/VUE/VUE的指令/",
      "headers": [
        {
          "level": 2,
          "title": "常用指令",
          "slug": "常用指令"
        },
        {
          "level": 3,
          "title": "v-if",
          "slug": "v-if"
        },
        {
          "level": 3,
          "title": "v-else",
          "slug": "v-else"
        },
        {
          "level": 3,
          "title": "v-show",
          "slug": "v-show"
        },
        {
          "level": 3,
          "title": "v-for",
          "slug": "v-for"
        },
        {
          "level": 3,
          "title": "v-bind",
          "slug": "v-bind"
        },
        {
          "level": 3,
          "title": "v-model",
          "slug": "v-model"
        },
        {
          "level": 3,
          "title": "v-on",
          "slug": "v-on"
        },
        {
          "level": 3,
          "title": "v-text",
          "slug": "v-text"
        },
        {
          "level": 2,
          "title": "自定义指令",
          "slug": "自定义指令"
        },
        {
          "level": 3,
          "title": "全局注册",
          "slug": "全局注册"
        },
        {
          "level": 3,
          "title": "局部组件注册",
          "slug": "局部组件注册"
        },
        {
          "level": 3,
          "title": "使用",
          "slug": "使用"
        }
      ]
    },
    {
      "title": "computed和watch",
      "frontmatter": {
        "title": "computed和watch",
        "date": "2022-7-21",
        "permalink": "/docs/VUE/computed和watch",
        "autoSort": 17,
        "tags": [
          "VUE"
        ],
        "categories": [
          "VUE"
        ]
      },
      "regularPath": "/VUE/computed%E5%92%8Cwatch.html",
      "relativePath": "VUE/computed和watch.md",
      "key": "v-317f572f",
      "path": "/docs/VUE/computed和watch/",
      "headers": [
        {
          "level": 2,
          "title": "computed计算属性",
          "slug": "computed计算属性"
        },
        {
          "level": 3,
          "title": "对象写法",
          "slug": "对象写法"
        },
        {
          "level": 3,
          "title": "函数写法",
          "slug": "函数写法"
        },
        {
          "level": 2,
          "title": "watch 监听属性",
          "slug": "watch-监听属性"
        },
        {
          "level": 3,
          "title": "对象写法",
          "slug": "对象写法-2"
        },
        {
          "level": 3,
          "title": "函数写法",
          "slug": "函数写法-2"
        }
      ]
    },
    {
      "title": "传参方式",
      "frontmatter": {
        "title": "传参方式",
        "date": "2022-7-19",
        "permalink": "/docs/VUE/传参方式",
        "autoSort": 18,
        "showSponsor": true,
        "tags": [
          "VUE"
        ],
        "categories": [
          "VUE"
        ]
      },
      "regularPath": "/VUE/%E4%BC%A0%E5%8F%82%E6%96%B9%E5%BC%8F.html",
      "relativePath": "VUE/传参方式.md",
      "key": "v-7368a04b",
      "path": "/docs/VUE/传参方式/",
      "headers": [
        {
          "level": 2,
          "title": "父子传参",
          "slug": "父子传参"
        },
        {
          "level": 3,
          "title": "父组件向子组件传参",
          "slug": "父组件向子组件传参"
        },
        {
          "level": 3,
          "title": "子组件向父组件传参",
          "slug": "子组件向父组件传参"
        },
        {
          "level": 2,
          "title": "eventBus",
          "slug": "eventbus"
        },
        {
          "level": 2,
          "title": "VUEX",
          "slug": "vuex"
        },
        {
          "level": 3,
          "title": "vuex的五个核心模块",
          "slug": "vuex的五个核心模块"
        },
        {
          "level": 3,
          "title": "使用",
          "slug": "使用"
        },
        {
          "level": 3,
          "title": "辅助函数  调用VUEX模块",
          "slug": "辅助函数-调用vuex模块"
        },
        {
          "level": 3,
          "title": "vx缓存数据",
          "slug": "vx缓存数据"
        }
      ]
    },
    {
      "title": "列表滚动",
      "frontmatter": {
        "title": "列表滚动",
        "date": "2022-6-30",
        "permalink": "/docs/VUE/列表滚动",
        "tags": [
          "VUE"
        ],
        "categories": [
          "VUE"
        ]
      },
      "regularPath": "/VUE/%E5%88%97%E8%A1%A8%E6%BB%9A%E5%8A%A8.html",
      "relativePath": "VUE/列表滚动.md",
      "key": "v-d6c13f38",
      "path": "/docs/VUE/列表滚动/",
      "headers": [
        {
          "level": 2,
          "title": "安装",
          "slug": "安装"
        },
        {
          "level": 2,
          "title": "使用",
          "slug": "使用"
        },
        {
          "level": 3,
          "title": "注册组件",
          "slug": "注册组件"
        },
        {
          "level": 3,
          "title": "使用组件",
          "slug": "使用组件"
        },
        {
          "level": 2,
          "title": "配置",
          "slug": "配置"
        }
      ]
    },
    {
      "title": "生命周期",
      "frontmatter": {
        "title": "生命周期",
        "date": "2022-7-25",
        "permalink": "/docs/VUE/生命周期",
        "autoSort": 16,
        "tags": [
          "VUE"
        ],
        "categories": [
          "VUE"
        ]
      },
      "regularPath": "/VUE/%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F.html",
      "relativePath": "VUE/生命周期.md",
      "key": "v-4dce1a64",
      "path": "/docs/VUE/生命周期/",
      "headers": [
        {
          "level": 2,
          "title": "什么是生命周期",
          "slug": "什么是生命周期"
        },
        {
          "level": 2,
          "title": "生命周期大全",
          "slug": "生命周期大全"
        },
        {
          "level": 3,
          "title": "beforeCreate",
          "slug": "beforecreate"
        },
        {
          "level": 3,
          "title": "created",
          "slug": "created"
        },
        {
          "level": 3,
          "title": "beforeMount",
          "slug": "beforemount"
        },
        {
          "level": 3,
          "title": "mounted",
          "slug": "mounted"
        },
        {
          "level": 3,
          "title": "beforeUpdate",
          "slug": "beforeupdate"
        },
        {
          "level": 3,
          "title": "updated",
          "slug": "updated"
        },
        {
          "level": 3,
          "title": "activated",
          "slug": "activated"
        },
        {
          "level": 3,
          "title": "deactivated",
          "slug": "deactivated"
        },
        {
          "level": 3,
          "title": "beforeUnmount",
          "slug": "beforeunmount"
        },
        {
          "level": 3,
          "title": "unmounted",
          "slug": "unmounted"
        },
        {
          "level": 2,
          "title": "曦杨常用的生命周期",
          "slug": "曦杨常用的生命周期"
        }
      ]
    },
    {
      "title": "组件缓存",
      "frontmatter": {
        "title": "组件缓存",
        "date": "2022-7-25",
        "permalink": "/docs/VUE/组件缓存",
        "autoSort": 15,
        "tags": [
          "VUE"
        ],
        "categories": [
          "VUE"
        ]
      },
      "regularPath": "/VUE/%E7%BB%84%E4%BB%B6%E7%BC%93%E5%AD%98.html",
      "relativePath": "VUE/组件缓存.md",
      "key": "v-a9ea0072",
      "path": "/docs/VUE/组件缓存/",
      "headers": [
        {
          "level": 2,
          "title": "什么是组件缓存？",
          "slug": "什么是组件缓存"
        },
        {
          "level": 2,
          "title": "组件缓存的优化写法",
          "slug": "组件缓存的优化写法"
        },
        {
          "level": 3,
          "title": "在路由表中定义一些标识",
          "slug": "在路由表中定义一些标识"
        },
        {
          "level": 3,
          "title": "app.vue判断",
          "slug": "app-vue判断"
        }
      ]
    },
    {
      "title": "路由",
      "frontmatter": {
        "title": "路由",
        "date": "2022-7-26",
        "permalink": "/docs/VUE/路由",
        "autoSort": 15,
        "tags": [
          "VUE"
        ],
        "categories": [
          "VUE"
        ]
      },
      "regularPath": "/VUE/%E8%B7%AF%E7%94%B1.html",
      "relativePath": "VUE/路由.md",
      "key": "v-d3a634e2",
      "path": "/docs/VUE/路由/",
      "headers": [
        {
          "level": 2,
          "title": "基本介绍",
          "slug": "基本介绍"
        },
        {
          "level": 2,
          "title": "安装",
          "slug": "安装"
        },
        {
          "level": 2,
          "title": "router组件",
          "slug": "router组件"
        },
        {
          "level": 3,
          "title": "router-link",
          "slug": "router-link"
        },
        {
          "level": 3,
          "title": "router-view",
          "slug": "router-view"
        },
        {
          "level": 2,
          "title": "获取路由",
          "slug": "获取路由"
        },
        {
          "level": 3,
          "title": "完整路由 this.$router",
          "slug": "完整路由-this-router"
        },
        {
          "level": 3,
          "title": "当前路由 this.$route",
          "slug": "当前路由-this-route"
        },
        {
          "level": 2,
          "title": "路由跳转",
          "slug": "路由跳转"
        },
        {
          "level": 2,
          "title": "路由传参",
          "slug": "路由传参"
        },
        {
          "level": 2,
          "title": "动态路由",
          "slug": "动态路由"
        },
        {
          "level": 2,
          "title": "重定向",
          "slug": "重定向"
        },
        {
          "level": 2,
          "title": "路由守卫",
          "slug": "路由守卫"
        },
        {
          "level": 3,
          "title": "全局守卫",
          "slug": "全局守卫"
        },
        {
          "level": 3,
          "title": "路由独享",
          "slug": "路由独享"
        },
        {
          "level": 3,
          "title": "组件守卫",
          "slug": "组件守卫"
        }
      ]
    },
    {
      "title": "点位聚合",
      "frontmatter": {
        "title": "点位聚合",
        "date": "2022-8-17",
        "permalink": "/docs/cesium三维地图/",
        "autoSort": 15,
        "tags": [
          "cesium三维地图"
        ],
        "categories": [
          "cesium三维地图"
        ]
      },
      "regularPath": "/cesium%E4%B8%89%E7%BB%B4%E5%9C%B0%E5%9B%BE/%E7%82%B9%E4%BD%8D%E8%81%9A%E5%90%88.html",
      "relativePath": "cesium三维地图/点位聚合.md",
      "key": "v-ee7ffc08",
      "path": "/docs/cesium三维地图/",
      "headers": [
        {
          "level": 2,
          "title": "撒点",
          "slug": "撒点"
        },
        {
          "level": 2,
          "title": "聚合",
          "slug": "聚合"
        },
        {
          "level": 2,
          "title": "geojson",
          "slug": "geojson"
        }
      ]
    },
    {
      "title": "地图坐标以及点击弹框",
      "frontmatter": {
        "title": "地图坐标以及点击弹框",
        "date": "2022-8-16",
        "permalink": "/docs/cesium三维地图/地图坐标以及点击弹框",
        "autoSort": 18,
        "tags": [
          "cesium三维地图"
        ],
        "categories": [
          "cesium三维地图"
        ]
      },
      "regularPath": "/cesium%E4%B8%89%E7%BB%B4%E5%9C%B0%E5%9B%BE/%E5%9C%B0%E5%9B%BE%E5%9D%90%E6%A0%87%E4%BB%A5%E5%8F%8A%E7%82%B9%E5%87%BB%E5%BC%B9%E6%A1%86.html",
      "relativePath": "cesium三维地图/地图坐标以及点击弹框.md",
      "key": "v-187027f6",
      "path": "/docs/cesium三维地图/地图坐标以及点击弹框/",
      "headers": [
        {
          "level": 2,
          "title": "点位显示",
          "slug": "点位显示"
        },
        {
          "level": 2,
          "title": "点击坐标弹框显示",
          "slug": "点击坐标弹框显示"
        },
        {
          "level": 2,
          "title": "定位中心点在地图中间",
          "slug": "定位中心点在地图中间"
        }
      ]
    },
    {
      "title": "坐标地面闪烁",
      "frontmatter": {
        "title": "坐标地面闪烁",
        "date": "2022-8-16",
        "permalink": "/docs/cesium三维地图/坐标地面闪烁",
        "autoSort": 17,
        "tags": [
          "cesium三维地图"
        ],
        "categories": [
          "cesium三维地图"
        ]
      },
      "regularPath": "/cesium%E4%B8%89%E7%BB%B4%E5%9C%B0%E5%9B%BE/%E5%9D%90%E6%A0%87%E5%9C%B0%E9%9D%A2%E9%97%AA%E7%83%81.html",
      "relativePath": "cesium三维地图/坐标地面闪烁.md",
      "key": "v-2265c176",
      "path": "/docs/cesium三维地图/坐标地面闪烁/"
    },
    {
      "title": "cesium配置",
      "frontmatter": {
        "title": "cesium配置",
        "date": "2022-8-16",
        "permalink": "/docs/cesium三维地图/cesium配置",
        "autoSort": 19,
        "tags": [
          "cesium三维地图"
        ],
        "categories": [
          "cesium三维地图"
        ]
      },
      "regularPath": "/cesium%E4%B8%89%E7%BB%B4%E5%9C%B0%E5%9B%BE/cesium%E9%85%8D%E7%BD%AE.html",
      "relativePath": "cesium三维地图/cesium配置.md",
      "key": "v-de48b46a",
      "path": "/docs/cesium三维地图/cesium配置/",
      "headers": [
        {
          "level": 2,
          "title": "基本配置",
          "slug": "基本配置"
        },
        {
          "level": 3,
          "title": "在main.js中引入cesium",
          "slug": "在main-js中引入cesium"
        },
        {
          "level": 3,
          "title": "配置token",
          "slug": "配置token"
        },
        {
          "level": 2,
          "title": "Cesium地图展示简单配置",
          "slug": "cesium地图展示简单配置"
        },
        {
          "level": 2,
          "title": "初始位置",
          "slug": "初始位置"
        }
      ]
    },
    {
      "title": "添加一个立方体",
      "frontmatter": {
        "title": "添加一个立方体",
        "date": "2022-8-18",
        "permalink": "/docs/cesium三维地图/添加一个立方体",
        "autoSort": 18,
        "tags": [
          "cesium三维地图"
        ],
        "categories": [
          "cesium三维地图"
        ]
      },
      "regularPath": "/cesium%E4%B8%89%E7%BB%B4%E5%9C%B0%E5%9B%BE/%E6%B7%BB%E5%8A%A0%E4%B8%80%E4%B8%AA%E7%AB%8B%E6%96%B9%E4%BD%93.html",
      "relativePath": "cesium三维地图/添加一个立方体.md",
      "key": "v-0ddcc835",
      "path": "/docs/cesium三维地图/添加一个立方体/",
      "headers": [
        {
          "level": 2,
          "title": "添加一个立方体盒子",
          "slug": "添加一个立方体盒子"
        },
        {
          "level": 2,
          "title": "设置缩放最大最小限制",
          "slug": "设置缩放最大最小限制"
        }
      ]
    },
    {
      "title": "点位起飞并有落地线",
      "frontmatter": {
        "title": "点位起飞并有落地线",
        "date": "2022-8-17",
        "permalink": "/docs/cesium三维地图/点位起飞并有落地线",
        "autoSort": 17,
        "tags": [
          "cesium三维地图"
        ],
        "categories": [
          "cesium三维地图"
        ]
      },
      "regularPath": "/cesium%E4%B8%89%E7%BB%B4%E5%9C%B0%E5%9B%BE/%E7%82%B9%E4%BD%8D%E8%B5%B7%E9%A3%9E%E5%B9%B6%E6%9C%89%E8%90%BD%E5%9C%B0%E7%BA%BF.html",
      "relativePath": "cesium三维地图/点位起飞并有落地线.md",
      "key": "v-88d19402",
      "path": "/docs/cesium三维地图/点位起飞并有落地线/",
      "headers": [
        {
          "level": 2,
          "title": "基础知识",
          "slug": "基础知识"
        },
        {
          "level": 2,
          "title": "点位起飞",
          "slug": "点位起飞"
        },
        {
          "level": 2,
          "title": "落地线",
          "slug": "落地线"
        }
      ]
    },
    {
      "title": "离线地图瓦片引用",
      "frontmatter": {
        "title": "离线地图瓦片引用",
        "date": "2022-11-9",
        "permalink": "/docs/cesium三维地图/离线地图瓦片引用",
        "autoSort": 14,
        "tags": [
          "cesium三维地图"
        ],
        "categories": [
          "cesium三维地图"
        ]
      },
      "regularPath": "/cesium%E4%B8%89%E7%BB%B4%E5%9C%B0%E5%9B%BE/%E7%A6%BB%E7%BA%BF%E5%9C%B0%E5%9B%BE%E7%93%A6%E7%89%87%E5%BC%95%E7%94%A8.html",
      "relativePath": "cesium三维地图/离线地图瓦片引用.md",
      "key": "v-db3d082a",
      "path": "/docs/cesium三维地图/离线地图瓦片引用/",
      "headers": [
        {
          "level": 2,
          "title": "下载瓦片",
          "slug": "下载瓦片"
        },
        {
          "level": 2,
          "title": "地图引入瓦片",
          "slug": "地图引入瓦片"
        }
      ]
    },
    {
      "title": "使用vuepress博客的初始化搭建",
      "frontmatter": {
        "title": "使用vuepress博客的初始化搭建",
        "date": "2022-6-23",
        "permalink": "/docs/博客/",
        "tags": [
          "博客"
        ],
        "categories": [
          "博客搭建"
        ]
      },
      "regularPath": "/%E5%8D%9A%E5%AE%A2%E6%90%AD%E5%BB%BA/",
      "relativePath": "博客搭建/README.md",
      "key": "v-ab19c3ae",
      "path": "/docs/博客/",
      "headers": [
        {
          "level": 2,
          "title": "准备工作",
          "slug": "准备工作"
        },
        {
          "level": 2,
          "title": "步骤",
          "slug": "步骤"
        },
        {
          "level": 3,
          "title": "1、引入vuepress-theme-reco主题",
          "slug": "_1、引入vuepress-theme-reco主题"
        },
        {
          "level": 3,
          "title": "2、配置项目",
          "slug": "_2、配置项目"
        },
        {
          "level": 3,
          "title": "3、启动项目",
          "slug": "_3、启动项目"
        }
      ]
    },
    {
      "title": "侧边栏",
      "frontmatter": {
        "title": "侧边栏",
        "date": "2022-06-29T00:00:00.000Z",
        "permalink": "/docs/博客/侧边栏",
        "tags": [
          "博客"
        ],
        "categories": [
          "博客搭建"
        ]
      },
      "regularPath": "/%E5%8D%9A%E5%AE%A2%E6%90%AD%E5%BB%BA/%E4%BE%A7%E8%BE%B9%E6%A0%8F.html",
      "relativePath": "博客搭建/侧边栏.md",
      "key": "v-21a94ace",
      "path": "/docs/博客/侧边栏/",
      "headers": [
        {
          "level": 2,
          "title": "对于markdown文件放置位置",
          "slug": "对于markdown文件放置位置"
        },
        {
          "level": 2,
          "title": "config设置",
          "slug": "config设置"
        },
        {
          "level": 2,
          "title": "自动侧边栏",
          "slug": "自动侧边栏"
        }
      ]
    },
    {
      "title": "插件大全",
      "frontmatter": {
        "title": "插件大全",
        "data": "2022-06-29T00:00:00.000Z",
        "permalink": "/docs/博客/插件大全",
        "tags": [
          "博客"
        ],
        "categories": [
          "博客搭建"
        ]
      },
      "regularPath": "/%E5%8D%9A%E5%AE%A2%E6%90%AD%E5%BB%BA/%E6%8F%92%E4%BB%B6%E5%A4%A7%E5%85%A8.html",
      "relativePath": "博客搭建/插件大全.md",
      "key": "v-5ef0e5ee",
      "path": "/docs/博客/插件大全/",
      "headers": [
        {
          "level": 2,
          "title": "1.PWA插件",
          "slug": "_1-pwa插件"
        },
        {
          "level": 2,
          "title": "2、看板娘插件",
          "slug": "_2、看板娘插件"
        },
        {
          "level": 2,
          "title": "3、公告插件",
          "slug": "_3、公告插件"
        },
        {
          "level": 2,
          "title": "4、音乐播放器插件",
          "slug": "_4、音乐播放器插件"
        },
        {
          "level": 2,
          "title": "5.页面彩带插件",
          "slug": "_5-页面彩带插件"
        },
        {
          "level": 2,
          "title": "6、页面樱花插件",
          "slug": "_6、页面樱花插件"
        },
        {
          "level": 2,
          "title": "7、趣味动态标题插件",
          "slug": "_7、趣味动态标题插件"
        },
        {
          "level": 2,
          "title": "8、随机名言插件",
          "slug": "_8、随机名言插件"
        },
        {
          "level": 2,
          "title": "9、代码块复制插件",
          "slug": "_9、代码块复制插件"
        },
        {
          "level": 2,
          "title": "10、鼠标点击特效插件",
          "slug": "_10、鼠标点击特效插件"
        },
        {
          "level": 2,
          "title": "11、自动侧边栏",
          "slug": "_11、自动侧边栏"
        }
      ],
      "excerpt": "<p>通过安装插件使我们的博客页面更加有逼格，炫酷。<a href=\"https://vuepress-theme-reco.recoluan.com/views/plugins/\" target=\"_blank\" rel=\"noopener noreferrer\">vuepress<OutboundLink/></a>提供啦部分内置插件。下面列出我了解的一些插件</p>\n"
    },
    {
      "title": "插件的使用",
      "frontmatter": {
        "title": "插件的使用",
        "date": "2022-6-27",
        "permalink": "/docs/博客/插件的使用",
        "tags": [
          "博客"
        ],
        "categories": [
          "博客搭建"
        ]
      },
      "regularPath": "/%E5%8D%9A%E5%AE%A2%E6%90%AD%E5%BB%BA/%E6%8F%92%E4%BB%B6%E7%9A%84%E4%BD%BF%E7%94%A8.html",
      "relativePath": "博客搭建/插件的使用.md",
      "key": "v-f4f8dc48",
      "path": "/docs/博客/插件的使用/",
      "headers": [
        {
          "level": 2,
          "title": "第一步安装插件",
          "slug": "第一步安装插件"
        },
        {
          "level": 2,
          "title": "第二部配置",
          "slug": "第二部配置"
        },
        {
          "level": 2,
          "title": "Attributes参数配置",
          "slug": "attributes参数配置"
        },
        {
          "level": 2,
          "title": "我的配置",
          "slug": "我的配置"
        }
      ]
    },
    {
      "title": "部署github",
      "frontmatter": {
        "title": "部署github",
        "date": "2022-6-28",
        "permalink": "/docs/博客/部署github和gitee",
        "tags": [
          "博客"
        ],
        "categories": [
          "博客搭建"
        ]
      },
      "regularPath": "/%E5%8D%9A%E5%AE%A2%E6%90%AD%E5%BB%BA/%E9%83%A8%E7%BD%B2github%E5%92%8Cgitee.html",
      "relativePath": "博客搭建/部署github和gitee.md",
      "key": "v-80e439d2",
      "path": "/docs/博客/部署github和gitee/",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "第一步在配置密钥",
          "slug": "第一步在配置密钥"
        },
        {
          "level": 2,
          "title": "第二步 创建一个github仓库",
          "slug": "第二步-创建一个github仓库"
        },
        {
          "level": 2,
          "title": "第三步 配置自动脚本",
          "slug": "第三步-配置自动脚本"
        }
      ]
    }
  ],
  "themeConfig": {}
}